### ISSUE TITLE
Repeat stan within one morpho instance

### ISSUE THREAD

**Issue by guiguem** [project8/morpho#44]
As suggested by Joe (08/11/17), a good feature would be to do both data generation and analysis within one morpho session.
It turned out Eleanor Graham has this feature in a customized morpho version (among other features).
Basically, the stan dictionary is replaced with a `which_stan` that is a list of stan dictionary.
Below is the Eleanor's implementation and the associated yaml file.

This feature might have a bad memory consumption as the objects need to be properly destroyed after each iteration, so we should be careful with that.

```python
#!/usr/bin/env python
#
# Morpho
#  -----------------------------------------------------
#  Authors: J. A. Formaggio <josephf@mit.edu>
# 			T. E. Weiss <tweiss@mit.edu>
#  			M. Guigue <mathieu.guigue@pnnl.gov>
#           J. N. Kofron <jared.kofron@gmail.com>
#

from __future__ import absolute_import

import os,sys
reload(sys)
sys.setdefaultencoding("utf-8")


import logging
logger = logging.getLogger('morpho')
logger.propagate = False
logger.setLevel(logging.DEBUG)
logger.handlers = []

base_format = '%(asctime)s{}[%(levelname)-8s] %(name)s(%(lineno)d) -> {}%(message)s'
import colorlog
fmt = colorlog.ColoredFormatter(
        base_format.format('%(log_color)s', '%(purple)s'),
        datefmt = '%Y-%m-%dT%H:%M:%SZ'[:-1],
        reset=True,
        )
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(fmt)
logger.addHandler(handler)

import time
import re
import random
import ast

import pystan
from pystan import stan
from yaml import load as yload
from argparse import ArgumentParser
from inspect import getargspec

import cPickle as pickle
from hashlib import md5
import importlib

class morpho(object):
    def read_param(self, yaml_data, node, default):
        data = yaml_data
        xpath = node.split('.')
        try:
            for path in xpath:
                data = data[path]
        except Exception as exc:
            if default == 'required':
                err = """FATAL: Configuration parameter {0} required but not\
                provided in config file!
                """.format(node)
                logger.debug(err)
                raise exc
            else:
                data = default
        return data

    def gen_arg_dict(self):
        d = self.__dict__
        sca = getargspec(stan_cache)
        sa = getargspec(stan)
        return {k: d[k] for k in (sa.args + sca.args) if k in d}

    def init_Stan_function(self):
        if isinstance(self.init_per_chain,list): # and self.init_per_chain.GetType().IsGenericType and self.init_per_chain.GetType().GetGenericTypeDefinition().IsAssignableFrom(typeof(List<>)):
            # init_per_chain is a list of dictionaries
            if self.chains >1 and len(self.init_per_chain)==1:
                dict_list = [self.init_per_chain[0]] * self.chains
                return dict_list
            elif len(self.init_per_chain)==self.chains :
                return self.init_per_chain
            else:
                logger.error('Number of chains is not equal to the size of the list of dictionaries')
                return self.init_per_chain
        elif isinstance(self.init_per_chain,dict): # and self.init_per_chain.GetType().IsGenericType and self.init_per_chain.GetType().GetGenericTypeDefinition().IsAssignableFrom(typeof(Dictionary<,>)):
            # init_per_chain is a dictionary
            if self.chains >1:
                return [self.init_per_chain] * self.chains
            else:
                return [self.init_per_chain]
        else:
            return self.init_per_chain

    def get_do_Stan(self):
        if self.do_stan==True:
            return True
        else:
            return False
    def get_do_prep(self):
        if self.do_preprocessing:
            return True
        else:
            return False
    def get_do_pp(self):
        if self.do_postprocessing:
            return True
        else:
            return False
    def get_do_plots(self):
        if self.do_plots:
            return True
        else:
            return False
    def get_wait(self):
        if self.wait:
            return True
        else:
            return False

    def __init__(self, yd):
        try:
            # Morpho steps
            self.do_preprocessing = self.read_param(yd, 'morpho.do_preprocessing', False)
            self.do_stan = self.read_param(yd, 'morpho.do_stan', True)
            self.do_postprocessing = self.read_param(yd, 'morpho.do_postprocessing', False)
            self.do_plots = self.read_param(yd, 'morpho.do_plots', False)
            self.wait = self.read_param(yd, 'morpho.wait_at_the_end', False)

            # batch identification
            if isinstance(args.job_id,(int,float,str)):
                self.seed=int(args.job_id)
		self.job_id = args.job_id
            else:
                self.job_id = 0

	    
            # Pre-processing configuration
            if self.do_preprocessing:
                self.prep_dict = self.read_param(yd, 'preprocessing.which_pp', None)

            #Stan configuration
            if self.do_stan:
                self.stan_dict = self.read_param(yd, 'stan.which_stan', None)
                
            # Post-processing configuration
            if self.do_postprocessing:
                self.pp_dict = self.read_param(yd, 'postprocessing.which_pp', None)

            # Plot configuration
            if self.do_plots:
                self.plot_dict = self.read_param(yd, 'plot.which_plot', None)

        except Exception as err:
            raise err

def stan_cache(model_code, function_files_location=None, model_name=None, cashe_dir='.',**kwargs):
    """Use just as you would `stan`"""


    theModel = open(model_code,'r+').read()
    match =  re.findall(r'\s*include\s*=\s*(?P<function_name>\w+)\s*;*',theModel)
    if function_files_location is not None:
        logger.debug('Looking for the functions to import in {}'.format(function_files_location))
        from os import listdir
        from os.path import isfile, join
        onlyfiles = [f for f in listdir(function_files_location) if isfile(join(function_files_location, f))]
    else:
        logger.debug('No functions file location given')
        onlyfiles = []
    for matches in match:
        found = False
        for filename in onlyfiles:
            if filename.endswith('.functions'):
                key = filename[:-10]
                if (key==matches):
                    StanFunctions = open(function_files_location+'/'+filename,'r+').read()
                    theModel = re.sub(r'\s*include\s*=\s*'+matches+'\s*;*\n',StanFunctions, theModel, flags=re.IGNORECASE)
                    found = True
                    logger.debug('Function file <{}> to import was found'.format(matches))
                    continue
        if found == False:
            logger.critical('A function <{}> to import is missing'.format(matches))
    logger.debug('Import function files: complete')

    code_hash = md5(theModel.encode('ascii')).hexdigest()
    if model_name is None:
        cache_fn = '{}/cached-model-{}.pkl'.format(cashe_dir, code_hash)
    else:
        cache_fn = '{}/cached-{}-{}.pkl'.format(cashe_dir, model_name, code_hash)

    cdir = os.path.dirname(cache_fn)
    if not os.path.exists(cdir):
        os.makedirs(cdir)
        logger.info("Creating 'cache' folder: {}".format(cdir))

    if (args.force_restart):
        logger.debug("Forced to create Stan cache!")
        sm = pystan.StanModel(model_code=theModel)
        if not args.no_cache:
            logger.debug("Saving Stan cache in {}".format(cache_fn))
            with open(cache_fn, 'wb') as f:
                pickle.dump(sm, f)
    else:
        try:
            logger.debug("Trying to load cached StanModel")
            sm = pickle.load(open(cache_fn, 'rb'))
        except:
            logger.debug("None exists -> creating Stan cache")
            sm = pystan.StanModel(model_code=theModel)
            if not args.no_cache:
                logger.debug("Saving Stan cache in {}".format(cache_fn))
                with open(cache_fn, 'wb') as f:
                    pickle.dump(sm, f, pickle.HIGHEST_PROTOCOL)
        else:
            logger.debug("Using cached StanModel: {}".format(cache_fn))

    if sa.out_cache_fn is not None:
        logger.debug("Saving cache file to {}".format(sa.out_cache_fn))
        cache_name_file = open(sa.out_cache_fn,'w+')
        cache_name_file.write(cache_fn)

    logger.info("Starting the sampling")
    text = "Parameters: \n"
    for key, value in kwargs.iteritems():
        if key is not "data":
            text = text + "{}\t{}\n".format(key,value)
        else:
            text = text + "data\t[...]\n"
    logger.info(text)
    # returns the arguments for sampling and the result of the sampling
    return kwargs, sm.sampling(**kwargs)

def parse_args():
    '''
    Parse the command line arguments provided to morpho.
    '''
    p = ArgumentParser(description='''
        An analysis tool for Project 8 data.
    ''')
    p.add_argument('-c','--config',
                   metavar='<configuration file>',
                   help='Full path to the configuration file used by morpho',
                   required=True)
    p.add_argument('--job_id',
                   metavar='<job_id>',
                   help='Job id number for batching',
                   required=False)
    p.add_argument('-s','--seed',
                   metavar='<seed>',
                   help='Add random seed number to file',
                   required=False)
    p.add_argument('-N_reps', '--N_reps',
                   metavar='<N_reps>',
                   help='Repeat all routines N times',
                   required=False)

    p.add_argument('-nas','--noautoseed',
                   action='store_false',
                   default=True,
                   help='Generate the seed based on the current time in ms',
                   required=False)
    p.add_argument('param',nargs='*',
                   default=False,
                   help='Manualy change of a parameter and its value')

    p.add_argument('-f','--force-restart',
                   action='store_true',
                   default=False,
                   help='Force the recompilation',
                   required=False)
    p.add_argument('-nc','--no-cache',
                    action='store_true',
                    default=False,
                    help='Do not save the Stan cache file',
                    required=False)
    return p.parse_args()

def update_from_arguments(the_dict,args):
    '''
    Update the dictionary extracted from the config file
    '''
    logger.debug('Update dict parameters')
    new_dict = the_dict
    for a_arg in args:
        result = a_arg.split('=')
        xpath = result[0].split('.')
        to_update_dict = {xpath[-1]:ast.literal_eval(result[1])}
        for path in reversed(xpath[:-1]):
            to_update_dict = {path:to_update_dict}
        new_dict = merge(new_dict,to_update_dict)
    return new_dict

def change_and_format(b):
    if b == 'True':
        return True
    elif b == 'False':
        return False
    else:
        try:
            a = float(b)
            return a
        except:
            return b

def merge(a, b, path=None):
    '''
    merges b into a
    '''
    if path is None: path = []
    for key in b:
        if key in a:
            if isinstance(a[key], dict) and isinstance(b[key], dict):
                merge(a[key], b[key], path + [str(key)])
            elif a[key] == b[key]:
                pass # same leaf value
            else:
                a[key] = change_and_format( b[key])
        else:
            a[key] = change_and_format( b[key])
    return a

def plot_result(conf, stanres):
    """
    Plot variables as specified.
    """
    fit = stanres.extract()
    if conf.plot_vars is not None:
        for var in conf.plot_vars:
            parname = var['variable']
            if parname not in fit:
                warning = """WARNING: data {0} not found in fit!  Skipping...
                """.format(parname)
                logger.debug(warning)
            else:
                stanres.plot(parname)

def write_result(conf, stanres, input_param):
    logger.info("Writing results!")
    from morpho.loader import pystanLoad as pyL
    ofilename = conf.out_fname
    rdir = os.path.dirname(ofilename)
    if not os.path.exists(rdir):
        os.makedirs(rdir)
        logger.info("Creating 'results' folder: {}".format(rdir))
    if (conf.job_id>0):
        ofilename = ofilename+'_'+conf.job_id
    if conf.out_format == 'hdf5':
        #ofilename = ofilename+'.h5'
        pyL.write_result_hdf5(sa, ofilename, stanres, input_param)

    if conf.out_format == 'root':
        ofilename = ofilename+'.root'
        pyL.stan_write_root(conf, ofilename, stanres, input_param)
    return stanres

def preprocessing(sa):
    # Generic function for creating the PreProcessing class
    if sa.prep_dict is None:
        logger.critical("preprocessing dict is None")
        return 0
    for minidict in sa.prep_dict:
        try:
            modulename = 'morpho.preprocessing.'+minidict['module_name']
            i = importlib.import_module("{}".format(modulename))
        except Exception as err:
            try:
                import imp
                i = imp.load_source(minidict['module_name'], minidict['module_name']+'.py')
                # i = importlib.import_module("{}".format(minidict['module_name']))
            except Exception as err:
                logger.critical(err)
                return 0
            else:
                logger.info("Doing preprocessing {} using {}".format(minidict['method_name'],minidict['module_name']+'.py'))
        else:
            logger.info("Doing preprocessing {} using {}".format(minidict['method_name'],modulename))

        try:
            getattr(i,minidict['method_name'])(minidict)
        except Exception as err:
            logger.critical(err)
    return 1

def fit(sa):
    for minidict in sa.stan_dict:
	# STAN model stuff
    	sa.model_code = minidict['model']['file']
        if 'function_files_location' in minidict['model']:
            sa.function_files_location = minidict['model']['function_files_location']
	else:
	    sa.function_files_location = None

        if 'model_name' in minidict['model']:
            sa.model_name = minidict['model']['model_name']
	else:
	    sa.model_name = None

        if 'cache' in minidict['model']:
            sa.cashe_dir = minidict['model']['cache']
        else:
            sa.cashe_dir = "./cache"

        # STAN data
        if 'data' in minidict:
            sa.datafiles = minidict['data']
        else:
            sa.datafiles = None

        # STAN run conditions
        if 'algorithm' in minidict['run']:
            sa.algorithm = minidict['run']['algorithm']
        else:
            sa.algorithm = "NUTS"

        if 'iter' in minidict['run']:
            sa.iter = int(minidict['run']['iter'])
        else:
            sa.iter = 2000

        if 'warmup' in minidict['run']:
            sa.warmup = int(minidict['run']['warmup'])
        else:
            sa.warmup = (sa.iter)/2

        if 'chain' in minidict['run']:    
            sa.chains = int(minidict['run']['chain'])
        else:
            sa.chains = 4

        if 'n_jobs' in minidict['run']:
            sa.n_jobs = int(minidict['run']['n_jobs'])
        else:
            sa.n_jobs = -1

        #file for storing raw data from each Stan iteration
        if 'sample_file' in minidict['run']:
            sa.sample_file = minidict['run']['sample_file']
        else:
            sa.sample_file = None

        # Adding a seed based on extra arguments, current time
        if isinstance(args.seed,(int,float,str)):
            sa.seed=int(args.seed)
        elif args.noautoseed:
            sa.seed = int(random.random()*1000000000) # seed based on random.random and the current system time
            logger.debug("Autoseed activated")
        else:
            sa.seed = int(minidict['run']['seed'])
            logger.debug("seed = {}".format(sa.seed))

        if 'thin' in minidict['run']:
            sa.thin = int(minidict['run']['thin'])
        else:
            sa.thin = 1

        if 'init' in minidict['run']:
            sa.init_per_chain = minidict['run']['init']
            sa.init = sa.init_Stan_function()

        if 'control' in minidict['run']:
            if isinstance(minidict['run']['control'],dict):
                sa.control = minidict['run']['control']
            else:
                logger.debug("stan.run.control should be a dict: {}",str(minidict['run']['control']))

        # plot and print information
        if 'plot' in minidict:
            sa.plot_vars = minidict['plot']
        else:
            sa.plot_vars = None

        # output information
        if 'format' in minidict['output']:
            sa.out_format = minidict['output']['format']
        else:
            sa.out_format = 'root'

        if 'name' in minidict['output']:    
            sa.out_fname = minidict['output']['name']
        else:
            sa.out_fname = 'stan_out.root'

        if 'option' in minidict['output']:
            sa.out_option = minidict['output']['option']
        else:
            sa.out_option = 'RECREATE'

        if 'tree' in minidict['output']:
            sa.out_tree = minidict['output']['tree']
        else:
            sa.out_tree = None

        if 'branches' in minidict['output']:
            sa.out_branches = minidict['output']['branches']
        else:
            sa.out_branches = None

        if 'inc_warmup' in minidict['output']:
            sa.out_inc_warmup = minidict['output']['inc_warmup']
        else:
            sa.out_inc_warmup = None

        if 'config' in  minidict['output']:
            sa.out_cfg = minidict['output']['config']
        else:
            sa.out_cfg = None

        # Outputted pickled fit filename
        if 'fit' in minidict['output']:
            sa.out_fit = minidict['output']['fit']
        else:
            sa.out_fit = None

        # Outputted text file containing name of cache file
        if 'save_cache_name' in minidict['output']:
            sa.out_cache_fn = minidict['output']['save_cache_name']
        else:
            sa.out_cache_fn = None
            
        try:
            logger.info("Doing MC with Stan")
            if sa.datafiles is not None:
                logger.debug("Loading datafiles")
                from morpho.loader import pystanLoad as pyL
                sa.data = pyL.stan_data_files(sa.datafiles)
                input_param, result = stan_cache(**(sa.gen_arg_dict()))
        except Exception as err:
            logger.critical(err)
            sys.exit(2)
        try:
            logger.info("Saving results")
            stanres = write_result(sa, result, input_param)
            if sa.out_fit != None:
                save_object(stanres, sa.out_fit)
                logger.debug('Saved fit in {}'.format(sa.out_fit))
        except Exception as err:
            logger.critical(err)
            sys.exit(2)
    return 1

def postprocessing(sa):
    # Generic function for creating the PostProcessing class
    if sa.pp_dict is None:
        logger.critical("postprocessing dict is None")
        return 0
    for minidict in sa.pp_dict:
        try:
            modulename = 'morpho.postprocessing.'+minidict['module_name']
            i = importlib.import_module("{}".format(modulename))
        except Exception as err:
            try:
                import imp
                i = imp.load_source(minidict['module_name'], minidict['module_name']+'.py')
                # i = importlib.import_module("{}".format(minidict['module_name']))
            except Exception as err:
                logger.critical(err)
                return 0
            else:
                logger.info("Doing postprocessing {} using {}".format(minidict['method_name'],minidict['module_name']+'.py'))
        else:
            logger.info("Doing postprocessing {} using {}".format(minidict['method_name'],modulename))

        try:
            getattr(i,minidict['method_name'])(minidict)
        except Exception as err:
            logger.critical(err)
    return 1

def plotting(sa):
    # Generic function for plotting
    list_canvas = []
    if sa.plot_dict is None:
        logger.critical("plot dict is None")
        return 0
    for minidict in sa.plot_dict:
        try:
            modulename = 'morpho.plot.'+minidict['module_name']
            i = importlib.import_module("{}".format(modulename))
        except Exception as err:
            try:
                import imp
                i = imp.load_source(minidict['module_name'], minidict['module_name']+'.py')
                # i = importlib.import_module("{}".format(minidict['module_name']))
            except Exception as err:
                logger.critical(err)
                return 0
            else:
                logger.info("Doing plot {} using {}".format(minidict['method_name'],minidict['module_name']+'.py'))
        else:
            logger.info("Doing plot {} using {}".format(minidict['method_name'],modulename))

        try:
            list_canvas.append(getattr(i,minidict['method_name'])(minidict))
        except Exception as err:
            logger.critical(err)
            return 0
    return list_canvas

def save_object(obj, filename):
    logger.info("Saving into pickle file: {}".format(filename))
    with open(filename, 'wb') as output:
        pickle.dump(obj, output, pickle.HIGHEST_PROTOCOL)

if __name__ == '__main__':
    print('\n\
	                                           ..ZDD8.\n\
	                                        .?D?I.DD$D\n\
	                                       D$???8$IDD,$\n\
	                                     8N7ZI?III?DDD\n\
	                                   8DIII?I$???ID.,\n\
	                                 .$D78?OI?I7?INDDD\n\
	                          ..    DN$7$7IO8??+I?DDD\n\
	                          8    $D$$77I$7I?I??IDD\n\
 ~ND+II??I7NOO8.          D,     O    ZDZ$$7$8OZI77$O?DD)\n\
O.NN.I7?III?787INNZD..      M.   1   ZO$$ZZ$$777III?ID.8\n\
DDDN?IIIIIIIIII7$$$$DDZ8    .N  7   8OZZZZZ$$$7III??IDD=\n\
 D,DD?I????II87I77$$$ZZDD$~   N M  ZOOZZO$$$$$7I7II?OD.O\n\
  .:,NII$I?II7I8$$7$$ZZZZON8N  ND:ZDZZ8Z88OOO8777I?INDD.\n\
   DDDD7?IIII??77$$ZO$ZZZOOZND$DDZNZOZZZZ$$$$$$7III7N?\n\
     O.$8I?III?II$$$$$ZZZO8OND$DO8ZZZ$$Z$$$7$77ZIIIN\n\
      .DDNII?7IIZ7$$$8$7ZZZZ$ZZ8D$Z$Z7ZZZ$77$777I$D\n\
       D.,D??I?II7I7$$$$$$$ZZ$$DDD$$$$$7O$7777IIIZDD\n\
	 DDDOI?7I7777D$$O$ZO7$8ZD8N$$$O7$$7IOIII??DD.\n\
	  MDDD+?IIIZ$7$77$7$$$8$7MDD77I7ZIIIII??7IDD\n\
	   =D.DDII?III777Z777787I.D?I7O???IZ???I?8D.$\n\
	      ...DID?7I7I777I?I7ID  8I?III?7?II8?DDD.\n\
	        DDD77I$III?8?II??D  DI??????Z?I?DN.N\n\
	         NNDI????8???I?$??D N7?I?????OI?NDD.\n\
	          DDD??II?I??I?II?D +DI?I?I?II7ND+N\n\
	          `?D8?I+?I?I7II??NN D8?7?I???DNDN\n\
	           .D,DD??Z?III???DN  NN7?IIDDM.D\n\
	            `DDDDIO???IIINN    N.DDDNDNN\n\
	              .D.DDDN7IND~M     DNDDD.\n\
	                DDD.DDN.DD        ..\n\
	                  .7..ID$\n\
	                    ...')

    print('\n\
	                      _        \n\
	   _ __  ___ _ _ _ __| |_  ___ \n\
	  |    \/ _ \  _|  _ \   \/ _ \ \n\
	  |_|_|_\___/_| | .__/_||_\___/ \n\
	                |_|            ')

    args = parse_args()
    with open(args.config, 'r') as cfile:
	try:
	    cdata = yload(cfile)
	    if args.param:
	        cdata = update_from_arguments(cdata,args.param)
	    sa = morpho(cdata)
	except Exception as err:
	    logger.critical(err)
	    sys.exit(2)

        #repeat the process N_reps times if N_reps is specified
	if isinstance(args.N_reps,(int,float,str)):
	    N_reps=int(args.N_reps)
        else:
            N_reps = 1
            
	for i in range(N_reps):
            logger.info("Conducting experiment {} of {}!".format(i+1, N_reps))
	    if (sa.get_do_prep()):
	        preprocessing(sa)

	    if (sa.get_do_Stan()):
                fit(sa)

	    if (sa.get_do_pp()):
	        postprocessing(sa)

	    if (sa.get_do_plots()):
		list_canvas = plotting(sa)

	    if(sa.get_wait()):
	        raw_input('Press <ret> to end -> ')

	logger.info("This is all for now!")
```

```yaml
# This is a testing script which is supposed to make a linear fit.
morpho:
  do_stan: True
  # do_postprocessing: True
  do_plots: True
  
stan:
  which_stan:
    # Name of the model
    - name: "morpho_test"
      # Model, associateyd functions, cache folder
      model:
        file: "./examples/morpho_test/models/morpho_linear_fit.stan"
        function_file: None
        cache: "./examples/morpho_test/cache"
      # Input data
      data:
        files:
          - name: "./examples/morpho_test/data/input.data"
            format: "R"
    
      # parameters: None
      # Run parameters
      run:
        algorithm: "NUTS"
        iter: 1000
        warmup: 500
        chain: 2
        n_jobs: -1
        sample_file: "./examples/morpho_test/samples"

      # Output destination
      output:
        name: "./examples/morpho_test/results/morpho_linear_fit"
        format: "root"
        tree: "morpho_test"
        option: "RECREATE"
        inc_warmup: False
        branches:
          - variable: "slope"
            root_alias: "a"
          - variable: "intercept"
            root_alias: "b"
          - variable: "variance_y"
            root_alias: "variance"
          - variable: "lp_prob"
            root_alias: "LogLikelihood"
          - variable: "divergent__"
            root_alias: "divergence"
          - variable: "energy__"
            root_alias: "energy"
          - variable: "delta_energy__"
            root_alias: "delta_energy"
# plot to do
plot:
  which_plot:
    - method_name: histo
      module_name: histo
      title: "histo"
      input_file_name : "./examples/morpho_test/results/morpho_linear_fit.root"
      input_tree: "morpho_test"
      output_path: ./examples/morpho_test/results/
      data:
        - a
    - method_name: histo
      module_name: histo
      title: "histo"
      input_file_name : "./examples/morpho_test/results/morpho_linear_fit.root"
      input_tree: "morpho_test"
      output_path: ./examples/morpho_test/results/
      data:
        - b
    - method_name: histo
      module_name: histo
      title: "histo"
      input_file_name : "./examples/morpho_test/results/morpho_linear_fit.root"
      input_tree: "morpho_test"
      output_path: ./examples/morpho_test/results/
      data:
        - variance
    - method_name: aposteriori_distribution
      module_name: histo
      input_file_name : "./examples/morpho_test/results/morpho_linear_fit.root"
      input_tree: "morpho_test"
      root_plot_option: "cont"
      output_path: ./examples/morpho_test/results/
      title: aposteriori_morpho_test
      output_format: pdf
      output_width: 12000
      output_height: 1100
      data:
        - a
        - b
        - variance
```
